### ISSUE TITLE
ValueError: Unknown layer:version

### ISSUE THREAD

**Issue by zeroix15** [universvm/BacXeption#15]
installed all requirements, but got this error when running the main.py
/Users/alif/.virtualenvs/datascience/lib/python3.6/site-packages/skimage/transform/_warps.py:105: UserWarning: The default mode, 'constant', will be changed to 'reflect' in skimage 0.15.
  warn("The default mode, 'constant', will be changed to 'reflect' in "
/Users/alif/.virtualenvs/datascience/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
Loading model...
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    flat_results = predict_flatness(norm_cutouts, MODEL_DIR, LOSS_FUNC, OPTIMIZER, METRICS)
  File "/Users/alif/Downloads/bacxeption/predict/predict.py", line 34, in predict_flatness
    model = _load_model(model_path, loss_func, optimizer, metrics)
  File "/Users/alif/Downloads/bacxeption/predict/predict.py", line 18, in _load_model
    model = model_from_json(json.dumps(model_json))
  File "/Users/alif/.virtualenvs/datascience/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in model_from_json
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/alif/.virtualenvs/datascience/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/Users/alif/.virtualenvs/datascience/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown layer:version https://git-lfs.github.com/spec/v1
oid sha256:eb008e67f674a7bee4dcc1e16c33ee31b766de13dcf2e1212a782ee2bacb0c84
size 71265

**Comment by universvm** [comment]
Hey there! As you might have noticed you need to download the dataset with git lfs. 

Also, this project is rather outdated but feel free to contribute with Pull Requests :)

**Comment by zeroix15** [comment]
Thank you very much for the reply! I realize it later and that's why I closed the issue
sure! If I made any update, I'll pull request it
